site_name: Tutorial ISWC 2025
site_description: OWL or SHACL - A beginner's guide to making the right choice between OWL and SHACL.
site_author: Tara Raafat & Davide D'Amico
copyright: Copyright © 2025 Semantic Masterclass
site_url: https://semanticmasterclass.github.io/iswc2025/
repo_url: https://github.com/SemanticMasterclass/iswc2025
repo_name: SemanticMasterclass/iswc2025

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: amber
      accent: amber

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: amber
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: amber
      accent: amber
  
  logo: assets/logo.png

  icon:
    repo: fontawesome/brands/github
    logo:  fontawesome/solid/play
  
  favicon: assets/favicon.ico
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  # - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Preparation: preparation.md
  - SPARQL: sparql.md
  - SHACL: shacl.md
  - About: about.md